# Generated by Django 4.2.2 on 2023-06-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
