# Generated by Django 4.2.2 on 2023-06-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
